# SPDX-FileCopyrightText: 2020 Free Software Foundation Europe e.V.
# SPDX-License-Identifier: CC0-1.0
repos:
  - repo: local
    hooks:
      -   id: rake
          name: rake
          entry: rake
          language: ruby