version = 1

[[annotations]]
path = '.ruby-version'
SPDX-FileCopyrightText = "2025 Kerrick Long <me@kerricklong.com>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = 'Gemfile.lock'
SPDX-FileCopyrightText = "2025 Kerrick Long <me@kerricklong.com>"
SPDX-License-Identifier = "CC0-1.0"
